"""empty message

Revision ID: f4a2be5d1814
Revises: ccbd1d60124f
Create Date: 2022-11-30 23:13:15.182079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4a2be5d1814'
down_revision = 'ccbd1d60124f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.NUMERIC(),
               type_=sa.Boolean(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Boolean(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    # ### end Alembic commands ###
